spring.application.name=filet-crochet
server.port=9010
spring.data.mongodb.uri=${MONGO_APP_URL:mongodb://localhost:27017/test}
spring.data.mongodb.database=${MONGO_DATABASE:test}

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never

app.cors.allowed-origins=${CORS_ORIGINS:http://localhost:4200,http://localhost:5173}
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG

# OpenAPI / Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
